[package]
name = "winapi_to_json"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version="0.12.5", features=["blocking"] }
serde = { version="1.0.207", features=["derive"] }
serde_json = "1.0.124"
windows-metadata = "0.58.0"
