name: <img/src=x/onerror='alert()'>

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare_and_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare ENV vars
      run: echo "RELEASE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Build the project
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate the output
      run: cargo run
    - name: Create new release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE }}
        release_name: Release ${{ env.RELEASE }}
